### ISSUE TITLE
与 hexo 5 中config配置冲突

### ISSUE THREAD

**Issue by packyzbq** [coneycode/hexo-generator-baidu-sitemap#35]
你好，我最近使用 hexo 5 新搭建了一个blog，其url及注释是这样写的
```yaml
# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: http://xxxxx/blog
root: /blog/
permalink: /posts/:title-:year-:month-:day.html
```
最终生成的 sitemap 链接如下：
```
http://xxxxx/blog/blog//post/:title-:year-:month-:day.html
```
是否需要在拼接时，校验 root 存在，防止重复拼接呢？
