### ISSUE TITLE
配置语法上的一点小问题。

### ISSUE THREAD

**Issue by chitanda** [coneycode/hexo-generator-baidu-sitemap#5]
在hexo 3.1.1下，当同时使用`hexo-generator-baidu-sitemap`和`hexo-generator-sitemap`的时候，如果按照说明里的语法，配置文件缩进两空格的话，会导致`baidusitemap.xml`无法生成。
如下：
```
sitemap:
  path: sitemap.xml 
baidusitemap:
  path: baidusitemap.xml 
```
而当把配置项的空格缩进去掉的时候，就又正常了。
```
sitemap:
path: sitemap.xml 
baidusitemap:
path: baidusitemap.xml 
```
不知道其他人能不能重现。。如果可以的话建议说明里的配置项的空格缩进去掉。
